<?php
namespace Trigon\AlaliahCore\Model;

use Trigon\AlaliahCore\Schema;

defined( 'ABSPATH' ) || exit;

/**
 * Post type registration. Internal keys use the alaliah_ prefix; public URLs never do.
 */
final class PostTypes {

	public static function definitions(): array {
		return array(
			Schema::PROPERTY  => array(
				'plural'   => 'Properties',
				'singular' => 'Property',
				'slug'     => 'property',
				'archive'  => false,
				'rest'     => 'properties',
				'supports' => array( 'title', 'editor', 'thumbnail', 'author', 'revisions' ),
				'icon'     => 'dashicons-building',
				// Property URLs are generated by PropertyUrls (/property/{slug}-aa-1001/).
				'rewrite'  => false,
			),
			Schema::PROJECT   => array(
				'plural'   => 'Projects',
				'singular' => 'Project',
				'slug'     => 'projects',
				'archive'  => 'projects',
				'rest'     => 'projects',
				'supports' => array( 'title', 'editor', 'thumbnail', 'revisions' ),
				'icon'     => 'dashicons-admin-multisite',
			),
			Schema::DEVELOPER => array(
				'plural'   => 'Developers',
				'singular' => 'Developer',
				'archive_title' => 'All Developers',
				'slug'     => 'developers',
				'archive'  => 'developers',
				'rest'     => 'developers',
				'supports' => array( 'title', 'thumbnail', 'revisions' ),
				'icon'     => 'dashicons-hammer',
			),
			Schema::AREA      => array(
				'plural'   => 'Areas',
				'singular' => 'Area',
				'slug'     => 'areas',
				'archive'  => 'areas',
				'rest'     => 'areas',
				'supports' => array( 'title', 'editor', 'thumbnail', 'revisions' ),
				'icon'     => 'dashicons-location-alt',
			),
			Schema::AGENT     => array(
				'plural'   => 'Team',
				'singular' => 'Agent',
				'slug'     => 'team',
				'archive'  => 'team',
				'rest'     => 'team',
				'supports' => array( 'title', 'editor', 'thumbnail' ),
				'icon'     => 'dashicons-groups',
			),
			Schema::INSIGHT   => array(
				'plural'   => 'Insights',
				'singular' => 'Insight',
				'slug'     => 'insights',
				'archive'  => 'insights',
				'rest'     => 'insights',
				'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt', 'revisions' ),
				'icon'     => 'dashicons-media-document',
			),
		);
	}

	public static function register(): void {
		foreach ( self::definitions() as $key => $d ) {
			if ( post_type_exists( $key ) ) {
				continue;
			}
			register_post_type(
				$key,
				array(
					'labels'           => array(
						'name'          => $d['plural'],
						'singular_name' => $d['singular'],
						'menu_name'     => $d['plural'],
						'add_new_item'  => 'Add ' . strtolower( $d['singular'] ),
						'edit_item'     => 'Edit ' . strtolower( $d['singular'] ),
						'all_items'     => $d['archive_title'] ?? 'All ' . strtolower( $d['plural'] ),
						'archives'      => $d['archive_title'] ?? $d['plural'],
					),
					'public'           => true,
					'show_ui'          => true,
					'show_in_menu'     => true,
					'show_in_rest'     => true,
					'rest_base'        => $d['rest'],
					'has_archive'      => $d['archive'],
					'rewrite'          => array_key_exists( 'rewrite', $d ) ? $d['rewrite'] : array( 'slug' => $d['slug'], 'with_front' => false ),
					'query_var'        => Schema::PROPERTY === $key ? false : true,
					'supports'         => $d['supports'],
					'menu_icon'        => $d['icon'],
					'capability_type'  => 'post',
					'map_meta_cap'     => true,
					'hierarchical'     => false,
					'delete_with_user' => false,
				)
			);
		}
	}
}
